services:
  web:
    build:
      context: .          # uses Dockerfile in Campus-Bus-Tracker
      dockerfile: Dockerfile
    container_name: campus-bus-tracker
    ports:
      - "8081:80"         # http://localhost:8081
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: transit_db
      MYSQL_USER: transit_user
      MYSQL_PASSWORD: secret123
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"          # phpMyAdmin on http://localhost:8080
    environment:
      PMA_HOST: db
      PMA_USER: transit_user
      PMA_PASSWORD: secret123
    depends_on:
      - db

volumes:
  mysql_data:
